### ISSUE TITLE
Script for connecting to https://www.deepl.com/translator

### ISSUE THREAD

**Issue by rosros2000** [yoursdearboy/omegat-browser#1]
Dear Kirill,
would it be possible to adapt the google groove script 

for the deepl translator engine.
Something similar to the attachment.
TIA,
Rossano

[deepl_translator.zip](https://github.com/yoursdearboy/omegat-browser/files/1402153/deepl_translator.zip)

**Comment by yoursdearboy** [comment]
@rosros2000, sorry for a late reply, I'll look at it this week. Thx you.

**Comment by yoursdearboy** [comment]
Script added. Thank you again for contribution.
