### ISSUE TITLE
Google&Google Translation scripts are unavailable

### ISSUE THREAD

**Issue by Bingxin2779** [yoursdearboy/omegat-browser#12]
Hi, thank you for your generous contribution. I'm using the browser plugin now. I find that the Google&Google Translation scripts cannot work though I install them as your guide says. Deepl is ok. 
I will appreciate it if you check and figure that problem. Thanks again.

**Comment by yoursdearboy** [comment]
That's because of changes in Google Translate website. The [Google Translate script](https://raw.githubusercontent.com/yoursdearboy/omegat-browser/master/scripts/google_translate.groovy) updated.
