### ISSUE TITLE
Package build automation

### ISSUE THREAD

**Issue by miurahr** [yoursdearboy/omegat-browser#17]
Recent days, Github Actions are more and more popular.
We can improve  a release task with automated CI/CD technology.

If @yoursdearboy want, I can propose PR.

**Comment by yoursdearboy** [comment]
@miurahr That would be great! I thought about it, but never had time to add tests and builds.

Actually, what do you think if I add you as a collaborator or forking the repo? Because I rarely have time to work on it.

**Comment by miurahr** [comment]
Thank you for offering collaborator, but it is ok to be just a contributor because I have already had several plugins maintained, and I'd like to ask you to work as a reviewer :smile:
